name: vida_plus
description: Um aplicativo para gerenciamento de hábitos saudáveis.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Firebase
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.3
  firebase_storage: ^11.2.8
  
  # State Management
  provider: ^6.0.5
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # Utils
  uuid: ^4.1.0
  intl: ^0.18.1
  flutter_local_notifications: ^16.0.0+1
  image_picker: ^1.0.4
  fl_chart: ^0.64.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/